### ISSUE TITLE
[FEATURE]German Language Support

### ISSUE THREAD

**Issue by SirMotte** [johnnolan/encounter-stats#273]
I just added in the German language strings using the Weblate link. They will probably need a rewrite here and there if they turn out to be cut off. As soon as they are included in the module, I will adjust them if need be.

**Comment by johnnolan** [comment]
Thanks for this @SirMotte, really appreciated! I haven't got a Pull Request about it yet in this repository, there may a button you need to press to say done that will then allow me to add it to the module.

Can you double check weblate and check you have finalised the translations, it should then create a Pull Request here https://github.com/johnnolan/encounter-stats/pulls for me to add your translations.

**Comment by SirMotte** [comment]
> Thanks for this @SirMotte, really appreciated! I haven't got a Pull Request about it yet in this repository, there may a button you need to press to say done that will then allow me to add it to the module.
> 
> Can you double check weblate and check you have finalised the translations, it should then create a Pull Request here https://github.com/johnnolan/encounter-stats/pulls for me to add your translations.

You're welcome. The pull request is generated automatically after 24hours, once the translation is done :).
![grafik](https://user-images.githubusercontent.com/82598692/192953135-1b9e277e-4aa2-4a21-8603-780ef2e870f6.png)

**Comment by johnnolan** [comment]
Awesome, will give it a force pull as I am too impatient :)

**Comment by johnnolan** [comment]
Merge and in now with PR #274 version 1.10.4 - thanks again for your time on this!

**Comment by SirMotte** [comment]
> Merge and in now with PR #274 version 1.10.4 - thanks again for your time on this!

A pleasure. thank you for providing this wonderful tool!
