### ISSUE TITLE
[FEATURE] Displaying Roll Streaks

### ISSUE THREAD

**Issue by LukasPrism** [johnnolan/encounter-stats#298]
Please consider adding a feature that will broadcast consecutive identical rolls into chat. It's just a fun little thing but players do find it interesting if they roll the same number several times in a row. There's often some misremembering – I'm sure I've rolled 4 7's in a row now! This would help keep tabs on that.

As I'm typing this I'm thinking that this could be built out as far as you'd like to take it. For instance you could notify if a player achieves a 'kill streak' (ie. number of consecutive kills for a player before someone else gets one), or even a 'hit streak' – it would be impressive to see how many hits a character can get before a miss. And vice versa – it's always a laugh when a player has a terrible streak of misses in a row, especially when they're usually the main damage dealer.

Thanks so much!

**Comment by johnnolan** [comment]
Moved the feature hit and miss streaks to another issue as this will more than likely involve tighter integration with MidiQoL.

This feature will consist of recording d20 roll streaks and reported to the campaign stats.

If possible I will add a hook for custom events for a user to create when a streak happens or implement optional messaging to chat. May just do the optional chat message alert for now.
