### ISSUE TITLE
[BUG] Blank Pages on existing game world

### ISSUE THREAD

**Issue by UnoriginalDM** [johnnolan/encounter-stats#311]
**Describe the bug**
For one of my worlds, Encounter Stats does not work. In a fresh world, it does.

**What version of FoundryVTT are you using?**
Version 10.286

**To Reproduce**
1. Enable Encounter Stats
2. Start a mock combat and do a few turns to gather data
3. end combat
4. check for journal update
5. blank page found

**Expected behavior**
Journal page should have data gathered and displayed from the combat.

**Screenshots**
What happens in one of my existing worlds:
![image](https://user-images.githubusercontent.com/77896718/194193359-016262f3-c78b-4c4c-a48f-ec7c9301c003.png)

Working as intended on a fresh world:
![image](https://user-images.githubusercontent.com/77896718/194194490-82aaf594-2c04-4ef0-bb71-55e4bdf9206d.png)

**Additional context**
The module was working before maybe mid-September with a multitude of other modules active.

EDIT: I also tried to delete my game data using the button in the settings and reinstalling the module.

**Comment by johnnolan** [comment]
Hi, there is an existing bug at the moment which I will be fixing this weekend relating to multiple combats, see #306 and this looks like the same problem.

Can you try running in your browsers console (press f12 to bring it up) this command `game.combats.size`.

If it is 1 or more then there is another encounter active on another scene and it will need to be stopped. You can run the following to help you find where the encounter is active and stop combat in that scene `game.combats.map((m) => m.scene.name)`

![image](https://user-images.githubusercontent.com/5390820/194223721-4d284858-9f26-4dac-a837-b2e9e04448c3.png)

Once the bug has been sorted you will be able to have multiple combats again.

Hope that helps get you back on track for now

**Comment by UnoriginalDM** [comment]
Hey just following up, you were correct and resolved the issue. Thank you.
