### ISSUE TITLE
[FEATURE] investigate pf2e potential 

### ISSUE THREAD

**Issue by johnnolan** [johnnolan/encounter-stats#336]
**Describe the new feature**
A clear and concise description of what the feature is.

**Expected behavior**

**Additional Information**
Discord information here to see how the system works https://discord.com/channels/880968862240239708/880968862961655819/926307217395838976

Seems everything is pretty much built in without the need for handling multiple modules.

One is https://foundryvtt.com/packages/pf2e-persistent-damage

However need to look at hooks for events in pf2e and how I can get the same information or different out of it.

https://github.com/foundryvtt/pf2e/wiki

**Comment by weepingminotaur** [comment]
Looking forward to seeing where this goes!

**Comment by johnnolan** [comment]
Initial build released in #402

**Comment by LogosWorks** [comment]
Super excited for this!
