### ISSUE TITLE
[BUG] v10 compatibility warning on compendium configuration

### ISSUE THREAD

**Issue by kpd328** [johnnolan/encounter-stats#337]
**Describe the bug**
Foundry v10 throws a compatibility warning, specifically `[encounter-stats] The module "encounter-stats" contains compendium pack data which uses the deprecated "entity" field which must be migrated to "type"`.

**What version of FoundryVTT are you using?**
Version 10 Build 287

**To Reproduce**
1. Have the module installed
2. Load up foundry v10

**Expected behavior**
Warnings related to deprecated fields can and should be remedied as they are found. Opening issue with intent to open PR shortly.

**Screenshots**
![image](https://user-images.githubusercontent.com/16842320/197362931-5be1e317-4e01-47a3-8a34-dd508ee7fa86.png)

**Additional context**
I've already tested changing the field name manually and will be submitting a PR shortly.

**Comment by johnnolan** [comment]
Thanks for the issue and pr! I am on holiday at the minute until Friday but will probably merge tonight while away if all looks good, thanks again
