### ISSUE TITLE
[BUG] Custom Campaign Events not displaying in journal

### ISSUE THREAD

**Issue by UnoriginalDM** [johnnolan/encounter-stats#339]
**Describe the bug**
Custom Campaign events are not displaying in journal but are recorded in JSON file

**What version of FoundryVTT are you using?**
V10.288

**To Reproduce**
1. Create a custom event using one of the provided macros
2. Check Encounter Stats journal

**Expected behavior**
Custom campaign events to display in journal.

**Screenshots**
Journal missing custom campaign events
![image](https://user-images.githubusercontent.com/77896718/197396294-774b8053-3d97-4e88-88ce-5aac6806910c.png)

Custom event appears in exported JSON
![image](https://user-images.githubusercontent.com/77896718/197396337-f28d9e0d-1eea-48ce-8355-9ba0699b4b13.png)

**Additional context**
...

**Comment by johnnolan** [comment]
Thanks for raising the issue, I am back from holiday this Friday so will take a look then. In the meantime could you export your campaign stats and upload them to the issue and I can use that to debug the issue and fix it for you, thanks!

**Comment by UnoriginalDM** [comment]
No problem. If I figure it out in the meantime, I will let you know. Thanks in advance.

[encounter-stats-export-20221025.txt](https://github.com/johnnolan/encounter-stats/files/9865916/encounter-stats-export-20221025.txt)
