### ISSUE TITLE
[BUG] Combat Tracker in combination with monks little details

### ISSUE THREAD

**Issue by Hydroxi** [johnnolan/encounter-stats#384]
**Describe the bug**
When you pop-out the tracker and also have it opened in the sidebar, there is a loop which flickers the trackers.
happens in combination with monks little details

**What version of FoundryVTT are you using?**
Version 10 Build 288

**To Reproduce**
Create Combat
Begin combat
right-click combat symbol to popout extra combat window.
enjoy the flicker

**Expected behavior**
No flickering?

**Screenshots**
https://imgur.com/a/399QIB6

**Additional context**
Encounter Stats handlers.OnUpdateCombat No new round  - Logger.ts 7

**Comment by johnnolan** [comment]
Thanks for the bug submission, will get on this today.

Also referenced in bug ticket #383

**Comment by johnnolan** [comment]
That should now be fixed, I can no longer replicate the issue but if you still see the issue feel free to reopen this issue and let me know :)

**Comment by Hydroxi** [comment]
Works like a charm! Thanks!
