### ISSUE TITLE
[FEATURE] Track attack types like in DND5e mwak, rwak, etc

### ISSUE THREAD

**Issue by johnnolan** [johnnolan/encounter-stats#405]
**Describe the new feature**
A clear and concise description of what the feature is.

**Expected behavior**

**Additional Information**

Relates to #336

**Comment by orangepeelbeef** [comment]
pf2e (now?) has roll options to easily show you if it is melee attack or ranged attack
ranged-attack-roll and melee-attack-roll
<img width="483" alt="image" src="https://github.com/johnnolan/encounter-stats/assets/130179/91481569-525d-4216-9c39-9be08526c26b">
