### ISSUE TITLE
[FEATURE] Add support for "Ready Set Roll for D&D5e"

### ISSUE THREAD

**Issue by Sravdar** [johnnolan/encounter-stats#461]
**Describe the new feature**
Make stats work with ready set roll module's rolls.
https://github.com/MangoFVTT/fvtt-ready-set-roll-5e

**Expected behavior**
Expecting it to log round events when roll is made using this module.

**Additional Information**
I personally don't like midi-qol rolls and use this module (rewrite of discontinued "better rolls for 5e" module) in my campaigns. Can't imagine myself playing without it.

**Comment by johnnolan** [comment]
Thanks for this, a quick look at the module looks relatively nice to implement, will see if I can get this done within the next week
