### ISSUE TITLE
[BUG] Encounter Stats randomly fails to work during encounters [PF2e]

### ISSUE THREAD

**Issue by weepingminotaur** [johnnolan/encounter-stats#506]
Encounter Stats doesn't seem to be working for me after most combats. I wonder if there is an issue with the macro to toggle Encounter Stats tracking on and off? The setting toggle works but I've not had any success with stats being tracked after using it. Sorry to submit such a vague bug report, but this is what I've encountered. No console errors either.

**Comment by johnnolan** [comment]
Hi, a bit hectic at home for the next few weeks so will get to this as I can. In the mean time could you send me

* 2 of your exported players as JSON
* A screenshot of a encounter report

Enabling and disabling works for me so it may be an update to pf2e and specific skills that are not being tracked. The above info will allow me to replicate your setup better and dig deeper, thanks!

**Comment by weepingminotaur** [comment]
OK, no problem. I'll send you those files after my next session. Thanks for looking into this.

**Comment by weepingminotaur** [comment]
Had this happen again last session and a couple of weeks ago too. I will get info next session (I keep forgetting to check for console errors during combat).

**Comment by weepingminotaur** [comment]
I've had to disable this module, sadly, because the behaviour on Pf2e is too unpredictable. Many times, it fails to activate during a combat, and I haven't been able to reproduce how or why.

**Comment by johnnolan** [comment]
No problem and sorry its still causing issues. If you do get a chance to send through the JSON export of 2 or more of your player characters I can spend some time trying to play around this side to see what might be happening. If not no worries, totally understand!

Will close this ticket for now to keep things tidy but feel free to drop those files on the ticket and reopen if you want.
