### ISSUE TITLE
Creating Journal Entry, But No Data In Journal

### ISSUE THREAD

**Issue by carlbutz** [johnnolan/encounter-stats#623]
{"coreVersion":"11.313","modules":[{"key":"5e-statblock-importer","id":"5e-statblock-importer","name":"5e-statblock-importer","active":false,"version":"1.69"},{"key":"ATL","id":"ATL","name":"ATL","active":false,"version":"0.7.0"},{"key":"ActiveAuras","id":"ActiveAuras","name":"ActiveAuras","active":false,"version":"0.8.0"},{"key":"BatchPermissionsByFolder","id":"BatchPermissionsByFolder","name":"BatchPermissionsByFolder","active":false,"version":"0.0.2"},{"key":"Dynamic-Effects-SRD","id":"Dynamic-Effects-SRD","name":"Dynamic-Effects-SRD","active":false,"version":"6.0.01"},{"key":"EasyTable","id":"EasyTable","name":"EasyTable","active":false,"version":"1.3.3"},{"key":"MaterialDeck","id":"MaterialDeck","name":"MaterialDeck","active":false,"version":"1.5.1"},{"key":"TokensVisible","id":"TokensVisible","name":"TokensVisible","active":false,"version":"3.1.2"},{"key":"about-time","id":"about-time","name":"about-time","active":false,"version":"11.0.1"},{"key":"acelib","id":"acelib","name":"acelib","active":false,"version":"1.8.3"},{"key":"adv-reminder","id":"adv-reminder","name":"adv-reminder","active":false,"version":"3.2.1"},{"key":"advanced-macros","id":"advanced-macros","name":"advanced-macros","active":false,"version":"2.0.4"},{"key":"always-hp","id":"always-hp","name":"always-hp","active":false,"version":"11.07"},{"key":"autoanimations","id":"autoanimations","name":"autoanimations","active":false,"version":"4.2.67"},{"key":"automated-evocations","id":"automated-evocations","name":"automated-evocations","active":false,"version":"2.0.3"},{"key":"automated-polymorpher","id":"automated-polymorpher","name":"automated-polymorpher","active":false,"version":"v1.2.1"},{"key":"babonus","id":"babonus","name":"babonus","active":false,"version":"11.4.0"},{"key":"better-rolltables","id":"better-rolltables","name":"better-rolltables","active":false,"version":"2.0.18"},{"key":"calendar-weather","id":"calendar-weather","name":"calendar-weather","active":false,"version":"3.1.10"},{"key":"card-tokens","id":"card-tokens","name":"card-tokens","active":false,"version":"0.5.3"},{"key":"chris-premades","id":"chris-premades","name":"chris-premades","active":false,"version":"0.7.35"},{"key":"color-picker","id":"color-picker","name":"color-picker","active":false,"version":"1.3"},{"key":"colorsettings","id":"colorsettings","name":"colorsettings","active":false,"version":"2.9.1"},{"key":"combat-carousel","id":"combat-carousel","name":"combat-carousel","active":false,"version":"0.3.3"},{"key":"compendium-browser","id":"compendium-browser","name":"compendium-browser","active":false,"version":"0.8.2"},{"key":"compendium-folders","id":"compendium-folders","name":"compendium-folders","active":false,"version":"2.6.1"},{"key":"condition-automation","id":"condition-automation","name":"condition-automation","active":false,"version":"3.0.2"},{"key":"condition-lab-triggler","id":"condition-lab-triggler","name":"condition-lab-triggler","active":false,"version":"1.4.5"},{"key":"dae","id":"dae","name":"dae","active":true,"version":"11.0.18"},{"key":"data-inspector","id":"data-inspector","name":"data-inspector","active":false,"version":"4.5.0.2"},{"key":"dd-import","id":"dd-import","name":"dd-import","active":false,"version":"2.6.1"},{"key":"ddb-importer","id":"ddb-importer","name":"ddb-importer","active":false,"version":"3.4.77"},{"key":"df-architect","id":"df-architect","name":"df-architect","active":false,"version":"4.0.0"},{"key":"df-qol","id":"df-qol","name":"df-qol","active":false,"version":"1.8.0"},{"key":"df-scene-enhance","id":"df-scene-enhance","name":"df-scene-enhance","active":false,"version":"3.6.0"},{"key":"df-settings-clarity","id":"df-settings-clarity","name":"df-settings-clarity","active":false,"version":"3.3.0"},{"key":"df-templates","id":"df-templates","name":"df-templates","active":false,"version":"1.3.0"},{"key":"dfreds-convenient-effects","id":"dfreds-convenient-effects","name":"dfreds-convenient-effects","active":false,"version":"6.0.0"},{"key":"dfreds-droppables","id":"dfreds-droppables","name":"dfreds-droppables","active":false,"version":"3.0.1"},{"key":"dice-calculator","id":"dice-calculator","name":"dice-calculator","active":false,"version":"1.5.3"},{"key":"dlopen","id":"dlopen","name":"dlopen","active":false,"version":"1.0"},{"key":"easy-target","id":"easy-target","name":"easy-target","active":false,"version":"2.16"},{"key":"effectmacro","id":"effectmacro","name":"effectmacro","active":false,"version":"11.0.1"},{"key":"fa-battlemaps","id":"fa-battlemaps","name":"fa-battlemaps","active":false,"version":"1.0.41"},{"key":"find-the-culprit","id":"find-the-culprit","name":"find-the-culprit","active":false,"version":"1.4.6"},{"key":"forge-compendium-browser","id":"forge-compendium-browser","name":"forge-compendium-browser","active":false,"version":"1.4.0"},{"key":"forge-vtt-shared-compendiums-monster-manual","id":"forge-vtt-shared-compendiums-monster-manual","name":"forge-vtt-shared-compendiums-monster-manual","active":false,"version":"v1.0"},{"key":"forien-ammo-swapper","id":"forien-ammo-swapper","name":"forien-ammo-swapper","active":false,"version":"0.2.2"},{"key":"foundry-combat-focus","id":"foundry-combat-focus","name":"foundry-combat-focus","active":false,"version":"1.4.2"},{"key":"foundry_community_macros","id":"foundry_community_macros","name":"foundry_community_macros","active":false,"version":"10.4"},{"key":"foundryvtt-simple-calendar","id":"foundryvtt-simple-calendar","name":"foundryvtt-simple-calendar","active":false,"version":"2.4.3"},{"key":"furnace","id":"furnace","name":"furnace","active":false,"version":"2.6.1"},{"key":"fvtt-encounter-stats","id":"fvtt-encounter-stats","name":"fvtt-encounter-stats","active":true,"version":"0.22.2"},{"key":"fvtt-party-resources","id":"fvtt-party-resources","name":"fvtt-party-resources","active":false,"version":"1.6.0"},{"key":"fxmaster","id":"fxmaster","name":"fxmaster","active":false,"version":"4.0.2"},{"key":"gm-notes","id":"gm-notes","name":"gm-notes","active":false,"version":"8.8"},{"key":"gm-screen","id":"gm-screen","name":"gm-screen","active":false,"version":"4.0.4"},{"key":"initiative-double-click","id":"initiative-double-click","name":"initiative-double-click","active":false,"version":"1.7.1"},{"key":"item-piles","id":"item-piles","name":"item-piles","active":false,"version":"2.7.16"},{"key":"itemacro","id":"itemacro","name":"itemacro","active":false,"version":"1.10.0"},{"key":"itemcollection","id":"itemcollection","name":"itemcollection","active":false,"version":"11.0.3"},{"key":"jb2a_patreon","id":"jb2a_patreon","name":"jb2a_patreon","active":false,"version":"0.6.1"},{"key":"lessfog","id":"lessfog","name":"lessfog","active":false,"version":"0.11.1"},{"key":"lib-wrapper","id":"lib-wrapper","name":"lib-wrapper","active":true,"version":"1.12.13.0"},{"key":"lichtgeschwindigkeit","id":"lichtgeschwindigkeit","name":"lichtgeschwindigkeit","active":false,"version":"1.4.9"},{"key":"lmrtfy","id":"lmrtfy","name":"lmrtfy","active":false,"version":"3.1.8"},{"key":"lootsheetnpc5e","id":"lootsheetnpc5e","name":"lootsheetnpc5e","active":false,"version":"3.6.1"},{"key":"macroeditor","id":"macroeditor","name":"macroeditor","active":false,"version":"1.1.2"},{"key":"mcc","id":"mcc","name":"mcc","active":false,"version":"1.4.1"},{"key":"midi-qol","id":"midi-qol","name":"midi-qol","active":true,"version":"11.1.3"},{"key":"monks-active-tiles","id":"monks-active-tiles","name":"monks-active-tiles","active":false,"version":"11.11"},{"key":"monks-bloodsplats","id":"monks-bloodsplats","name":"monks-bloodsplats","active":false,"version":"11.06"},{"key":"monks-combat-details","id":"monks-combat-details","name":"monks-combat-details","active":false,"version":"11.08"},{"key":"monks-combat-marker","id":"monks-combat-marker","name":"monks-combat-marker","active":false,"version":"11.02"},{"key":"monks-hotbar-expansion","id":"monks-hotbar-expansion","name":"monks-hotbar-expansion","active":false,"version":"10.1"},{"key":"monks-little-details","id":"monks-little-details","name":"monks-little-details","active":false,"version":"11.05"},{"key":"monks-scene-navigation","id":"monks-scene-navigation","name":"monks-scene-navigation","active":false,"version":"11.02"},{"key":"monks-tokenbar","id":"monks-tokenbar","name":"monks-tokenbar","active":false,"version":"11.05"},{"key":"monks-wall-enhancement","id":"monks-wall-enhancement","name":"monks-wall-enhancement","active":false,"version":"11.02"},{"key":"multilevel-tokens","id":"multilevel-tokens","name":"multilevel-tokens","active":false,"version":"1.6.0"},{"key":"npcgen","id":"npcgen","name":"npcgen","active":false,"version":"1.1.0"},{"key":"permission_viewer","id":"permission_viewer","name":"permission_viewer","active":false,"version":"11.4"},{"key":"pick-up-stix","id":"pick-up-stix","name":"pick-up-stix","active":false,"version":"0.13.8"},{"key":"pin-cushion","id":"pin-cushion","name":"pin-cushion","active":false,"version":"1.9.10"},{"key":"popout","id":"popout","name":"popout","active":false,"version":"2.14"},{"key":"quick-encounters","id":"quick-encounters","name":"quick-encounters","active":false,"version":"1.2.1"},{"key":"ready-to-use-cards","id":"ready-to-use-cards","name":"ready-to-use-cards","active":false,"version":"1.12.3"},{"key":"resetdoorsandfog","id":"resetdoorsandfog","name":"resetdoorsandfog","active":false,"version":"1.0.1"},{"key":"scaleGrid","id":"scaleGrid","name":"scaleGrid","active":false,"version":"1.4.3"},{"key":"scene-packer","id":"scene-packer","name":"scene-packer","active":false,"version":"2.7.7"},{"key":"scenery","id":"scenery","name":"scenery","active":false,"version":"1.1.3"},{"key":"sequencer","id":"sequencer","name":"sequencer","active":false,"version":"3.1.4"},{"key":"settings-extender","id":"settings-extender","name":"settings-extender","active":false,"version":"1.2.2"},{"key":"simbuls-athenaeum","id":"simbuls-athenaeum","name":"simbuls-athenaeum","active":false,"version":"1.0.5"},{"key":"simbuls-creature-aide","id":"simbuls-creature-aide","name":"simbuls-creature-aide","active":false,"version":"1.1.4"},{"key":"simbuls-template-scaling","id":"simbuls-template-scaling","name":"simbuls-template-scaling","active":false,"version":"1.0.2"},{"key":"smart-doors","id":"smart-doors","name":"smart-doors","active":false,"version":"1.4.1"},{"key":"socketlib","id":"socketlib","name":"socketlib","active":true,"version":"1.0.13"},{"key":"split-journal","id":"split-journal","name":"split-journal","active":false,"version":"1.2.0"},{"key":"stairways","id":"stairways","name":"stairways","active":false,"version":"0.10.2"},{"key":"summoner","id":"summoner","name":"summoner","active":false,"version":"0.1.4"},{"key":"tagger","id":"tagger","name":"tagger","active":false,"version":"1.4.5"},{"key":"templatemacro","id":"templatemacro","name":"templatemacro","active":false,"version":"11.0.0"},{"key":"tidy-ui_game-settings","id":"tidy-ui_game-settings","name":"tidy-ui_game-settings","active":false,"version":"0.1.52"},{"key":"tidy5e-sheet","id":"tidy5e-sheet","name":"tidy5e-sheet","active":false,"version":"0.9.18"},{"key":"times-up","id":"times-up","name":"times-up","active":false,"version":"11.0.3"},{"key":"token-action-hud","id":"token-action-hud","name":"token-action-hud","active":false,"version":"3.0.21"},{"key":"token-action-hud-core","id":"token-action-hud-core","name":"token-action-hud-core","active":false,"version":"1.4.21"},{"key":"token-action-hud-dnd5e","id":"token-action-hud-dnd5e","name":"token-action-hud-dnd5e","active":false,"version":"1.4.13"},{"key":"token-attacher","id":"token-attacher","name":"token-attacher","active":false,"version":"v4.5.13"},{"key":"token-mold","id":"token-mold","name":"token-mold","active":false,"version":"2.20.3"},{"key":"tokenmagic","id":"tokenmagic","name":"tokenmagic","active":false,"version":"0.6.4.1"},{"key":"turnAlert","id":"turnAlert","name":"turnAlert","active":false,"version":"2.0.0"},{"key":"vision-5e","id":"vision-5e","name":"vision-5e","active":false,"version":"1.10.4"},{"key":"vueport","id":"vueport","name":"vueport","active":false,"version":"1.1"},{"key":"warpgate","id":"warpgate","name":"warpgate","active":false,"version":"1.19.0"},{"key":"weather-control","id":"weather-control","name":"weather-control","active":false,"version":"4.1.9"},{"key":"weatherblock","id":"weatherblock","name":"weatherblock","active":false,"version":"1.0.2"},{"key":"forge-vtt","id":"forge-vtt","name":"forge-vtt","active":true,"version":"1.10"},{"key":"forge-vtt-optional","id":"forge-vtt-optional","name":"forge-vtt-optional","active":false,"version":"1.1"}],"settings":[{"id":"fvtt-encounter-stats.enable","value":true},{"id":"fvtt-encounter-stats.enable_aoe_damage","value":false},{"id":"fvtt-encounter-stats.enable_monster_stats","value":true},{"id":"fvtt-encounter-stats.enable_journal_notification","value":false},{"id":"fvtt-encounter-stats.toggle_campaign_tracking_name","value":true},{"id":"fvtt-encounter-stats.enable_simple_calendar_integration","value":true},{"id":"midi-qol.EnableWorkflow","value":true},{"id":"midi-qol.AutoFastForwardAbilityRolls","value":true},{"id":"midi-qol.LateTargeting","value":"none"},{"id":"midi-qol.ItemRollButtons","value":true},{"id":"midi-qol.showGM","value":true},{"id":"midi-qol.ForceHideRoll","value":true},{"id":"midi-qol.DragDropTarget","value":false},{"id":"midi-qol.ConfigSettings","value":{"gmAutoAttack":true,"gmAutoFastForwardAttack":true,"gmAutoDamage":"onHit","gmAutoFastForwardDamage":true,"showItemDetails":"all","itemTypeList":["weapon","equipment","consumable","tool","loot","class","spell","feat","backpack"],"autoRollAttack":true,"autoFastForward":"all","autoTarget":"wallsBlockIgnoreDefeated","autoCheckHit":"all","autoCheckSaves":"all","hideRollDetails":"hitDamage","displaySaveDC":true,"checkSaveText":false,"autoRollDamage":"onHit","autoApplyDamage":"yesCard","damageImmunities":"immunityPhysical","autoItemEffects":"applyRemove","rangeTarget":"alwaysIgnoreDefeated","playerRollSaves":"letme","playerSaveTimeout":30,"rollNPCSaves":"auto","preRollChecks":false,"mergeCard":true,"mergeCardCondensed":true,"hideNPCNames":"","useTokenNames":true,"fullAuto":false,"allowUseMacro":true,"rollOtherDamage":"activation","removeButtons":"all","gmRemoveButtons":"all","concentrationAutomation":true,"singleConcentrationRoll":true,"optionalRules":{"actionSpecialDurationImmediate":false,"activeDefence":false,"activeDefenceShowGM":false,"challengeModeArmor":false,"challengeModeArmorScale":false,"checkFlanking":"off","checkRange":"longfail","coverCalculation":"none","displayBonusRolls":true,"criticalNat20":false,"criticalSaves":false,"distanceIncludesHeight":true,"incapacitated":true,"invisAdvantage":"RAW","maxDRValue":true,"DRAllPerDamageDetail":true,"nearbyAllyRanged":0,"nearbyFoe":5,"optionalCritRule":-1,"removeHiddenInvis":true,"wallsBlockRange":"center","mergeCardMulti":false,"enableddbGL":false,"enforceReactions":"all","recordAOO":"all","autoRerollInitiative":false,"invisVision":false,"vitalityResource":""},"optionalRulesEnabled":true,"defaultSaveMult":0.5,"keepRollStats":false,"saveStatsEvery":20,"playerStatsOnly":false,"removeConcentration":true,"usePlayerPortrait":false,"doReactions":"all","gmDoReactions":"all","reactionTimeout":30,"requiresTargets":"combat","showReactionAttackRoll":"all","autoCEEffects":"cepri","rollOtherSpellDamage":"none","promptDamageRoll":false,"gmHide3dDice":false,"ghostRolls":false,"gmFastForwardSpells":false,"fastForwardSpells":false,"accelKeysOverride":false,"enableddbGL":false,"showReactionChatMessage":false,"rollNPCLinkedSaves":"auto","gmConsumeResource":"none","consumeResource":"none","gmLateTargeting":"none","lateTargeting":"none","addWounded":50,"addDead":"overlay","convenientEffectsReaction":"Reaction","fixStickyKeys":true,"autoFailSavesFriendly":false,"worldKeyMappings":false,"toggleOptionalRules":false,"fumbleSound":"sounds/dice.wav","criticalSound":"sounds/dice.wav","diceSound":"sounds/dice.wav","rollChecksBlind":["none"],"rollSavesBlind":["none"],"rollSkillsBlind":["none"],"displaySaveAdvantage":true,"recordAOO":"none","enforceReactions":"none","enforceBonusActions":"none","playerDamageCard":"none","playerCardDamageDifferent":true,"displayHitResultNumeric":false,"rollAlternate":"off","allowActorUseMacro":true,"skillAbilityCheckAdvantage":true,"keyMapping":{"DND5E.Advantage":"altKey","DND5E.Disadvantage":"ctrlKey","DND5E.Critical":"altKey","DND5E.Versatile":"shiftKey"},"paranoidGM":false,"tempHPDamageConcentrationCheck":false,"showDSN":true,"showFastForward":true,"highlightSuccess":false,"confirmAttackDamage":"none","requireMagical":"off","itemRollStartWorkflow":false,"ignoreSpellReactionRestriction":false,"damageImmunityMultiplier":0,"damageResistanceMultiplier":0.5,"damageVulnerabilityMultiplier":2,"hidePlayerDamageCard":true,"attackPerTarget":false,"autoRemoveTemplate":true,"removeConcentrationEffects":"effects","undoWorkflow":false,"enforceSingleWeaponTarget":false,"quickSettings":true,"averageNPCDamage":false,"mergeCardMulti":false,"useCustomSounds":false}},{"id":"midi-qol.MidiSoundSettings","value":{}},{"id":"midi-qol.MidiSoundSettings-backup","value":{}},{"id":"midi-qol.CriticalDamageGM","value":"default"},{"id":"midi-qol.CriticalDamage","value":"default"},{"id":"midi-qol.AddChatDamageButtons","value":"none"},{"id":"midi-qol.ColoredBorders","value":"none"},{"id":"midi-qol.AutoRemoveTargets","value":"dead"},{"id":"midi-qol.playerControlsInvisibleTokens","value":false},{"id":"midi-qol.Debug","value":"none"},{"id":"midi-qol.debugCallTiming","value":false},{"id":"midi-qol.notificationVersion","value":"0.0.0"},{"id":"midi-qol.splashWarnings","value":true},{"id":"midi-qol.itemUseHooks","value":false},{"id":"midi-qol.last-run-version","value":"11.1.3"},{"id":"midi-qol.instanceId","value":"wJeIDSXLkUh4V7Ik"},{"id":"midi-qol.RollStats","value":{"4CxaGyUdgheltcUP":{"session":{"numAttacks":5,"numAttack20":0,"numAttackFumble":0,"numAttackCritical":0,"numAttackMisses":0,"attackRollsDiceTotal":56,"attackRollTotal":76,"numD20Rolls":0,"numDamageRolls":5,"damageApplied":51,"damageTotal":51},"lifetime":{"numAttacks":5,"numAttack20":0,"numAttackFumble":0,"numAttackCritical":0,"numAttackMisses":0,"attackRollsDiceTotal":56,"attackRollTotal":76,"numD20Rolls":0,"numDamageRolls":5,"damageApplied":51,"damageTotal":51},"itemStats":{"Battleaxe":{"name":"Battleaxe","session":{"numAttacks":5,"numAttack20":0,"numAttackFumble":0,"numAttackCritical":0,"numAttackMisses":0,"attackRollsDiceTotal":56,"attackRollTotal":76,"numD20Rolls":0,"numDamageRolls":5,"damageApplied":51,"damageTotal":51}}},"name":"test"},"ArhzuFJBRc9V7xLB":{"session":{"numAttacks":5,"numAttack20":0,"numAttackFumble":0,"numAttackCritical":0,"numAttackMisses":0,"attackRollsDiceTotal":56,"attackRollTotal":76,"numD20Rolls":0,"numDamageRolls":5,"damageApplied":51,"damageTotal":51},"lifetime":{"numAttacks":5,"numAttack20":0,"numAttackFumble":0,"numAttackCritical":0,"numAttackMisses":0,"attackRollsDiceTotal":56,"attackRollTotal":76,"numD20Rolls":0,"numDamageRolls":5,"damageApplied":51,"damageTotal":51},"itemStats":{"Battleaxe":{"name":"Battleaxe","session":{"numAttacks":5,"numAttack20":0,"numAttackFumble":0,"numAttackCritical":0,"numAttackMisses":0,"attackRollsDiceTotal":56,"attackRollTotal":76,"numD20Rolls":0,"numDamageRolls":5,"damageApplied":51,"damageTotal":51}}},"name":"cbutz-dm"}}}]}

**Comment by johnnolan** [comment]
Hi, thanks for the report, could you provide me with the following so I can delve a little deeper please?

* An export of the stats (you can export these from the module settings)
* When starting an encounter, are there any errors showing in the console, if so could you screenshot and add to this ticket please?

That will give me a place to start figuring out what might be the cause, thanks!

**Comment by carlbutz** [comment]
![image](https://github.com/johnnolan/encounter-stats/assets/69695792/38c9b7f8-407a-4f9c-ba0e-b8ab50d93693)
I do not see a way to export the statistics. I am sending a screen shot of what I have when Looking at the configure settings for the mod. 

When I do start combat I receive this error:
Handlers.js:56 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'round')
    at _updateRound (Handlers.js:56:12)
    at OnUpdateCombat (Handlers.js:148:9)
    at Object.fn (Hooks.js:87:7)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13679:13)
    at foundry.js:13652:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry.js:13652:33)

Hope this helps.

**Comment by johnnolan** [comment]
Yeah that helped massively, thank you, it looks like you are on a older version of the module. The best version to use is the latest with Foundry 10 or 11. 11 I can do bug fixes on but it should work with 11. What version of Foundry do you have installed? Can you try updating the module and see if it fixes the issue?

![image](https://github.com/johnnolan/encounter-stats/assets/5390820/d486e9f6-5bce-486b-bbbe-0c2f932ffa09)

**Comment by carlbutz** [comment]
It appears there are two versions of this on the Forge, I had the older one. Updating to the newest one worked in my test game.

Thanks for your help.
