### ISSUE TITLE
[BUG] using a health potion in PF2e causes console error

### ISSUE THREAD

**Issue by orangepeelbeef** [johnnolan/encounter-stats#629]
**Describe the bug**
Using a health potion causes a console error

**What version of FoundryVTT are you using?**
Foundry Version: 11.313

**What version of dnd5e or Pf2e are you using?**
Version: pf2e 5.7.2

**What roll module are you using?**

- [x ] None
- [ ] Midi-QOL
- [ ] Ready Set Roll for DND5e

**To Reproduce**
1. give a character a minor healing potion
2. Click on 'use healing potion minor'
3. open console log

**Screenshot any console errors**
<img width="757" alt="image" src="https://github.com/johnnolan/encounter-stats/assets/130179/3e4a1071-eda0-4c66-9793-549992f2e1c7">

**Screenshots**
<img width="224" alt="image" src="https://github.com/johnnolan/encounter-stats/assets/130179/7d9a2732-3a0c-45ab-9c7e-685ce4cb47e5">

**Additional context**
this item usage seems to show up as a damage roll, but the item property is null, there are no sub values.

**Comment by johnnolan** [comment]
Sorry about the delay on this one. I cannot replicate it this side, it looks like for some reason the healing potion does not belong to the actor when its used which is strange.

Can you export data and upload your character for me so I can import it into my Foundry and try running it here please?

![image](https://github.com/johnnolan/encounter-stats/assets/5390820/bae9602b-9177-43bb-b1a0-b8069d29241c)
