### ISSUE TITLE
[FEATURE] Hide roll streak message after hidden rolls

### ISSUE THREAD

**Issue by Co0nmz** [johnnolan/encounter-stats#631]
Please add an option to hide the roll streak message after hidden rolls since the mod currently gives away the result of hidden rolls if a roll streak happens.

**Comment by johnnolan** [comment]
So the module should do this already, I added the functionality a few weeks ago. Can you write down the steps to where you are seeing this?

For example if someone rolls with anything other than a Public Roll and gets a streak on that roll it shouldn't show. But I am wondering if there is a case that I have missed like user rolls hidden then changes to public, rolls and it shows a streak ruining the last hidden roll.

Could you confirm the following as well please so I can test

- PF2E or DND5e
- Foundry version
- version of the module you are running

**Comment by MaxPelly** [comment]
We get roll streak pop ups for hidden and blind rolls in out pf2e game with everything fully updated as well
